services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: fastapi_app
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=development

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend_app
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - fastapi
